Update workflow for deprecated set-env
Github Actions deprecated `set-env`:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

```
Error: The `set-env` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

The replacement is at
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files.