Fix forge start script to start under dataflow properly
Without this, we were running into error:

```
$ docker run -it sha256:da494990d59812644fdfd64c174e0b73051fdb478e7e3b7d0c25ed4c75dd75cb --logging_endpoint=localhost:12370 --control_endpoint=localhost:12371 --semi_persist_dir=/var/opt/google --id=sdk-0-0 --artifact_endpoint=localhost:12375 --provision_endpoint=localhost:12376
Traceback (most recent call last):
  File "/srv/start", line 30, in <module>
    os.execvp(command, sys.argv[1:])
  File "/srv/conda/envs/notebook/lib/python3.9/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/srv/conda/envs/notebook/lib/python3.9/os.py", line 616, in _execvpe
    raise last_exc
  File "/srv/conda/envs/notebook/lib/python3.9/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

Which makes sense, as sys.argv won't have these without the -